template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|{tools,requirements,.github}/**|-*.md']

  - labels: [source]
    patterns: ['wcmatch/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [docs]
    patterns: ['docs/**|*.md']

  - labels: [bre]
    patterns: ['**/*bre.py']

  - labels: [bregex]
    patterns: ['**/*bregex.py']

  - labels: [unicode]
    patterns: ['**/uniprops/**|tests/uniprops.py']

# Label management

labels:
- name: bre
  color: subcategory
  description: Related to backrefs in re library.

- name: bregex
  color: subcategory
  description: Related to backrefs in regex library.

- name: unicode
  color: subcategory
  description: Related to Unicode handling.
