strictness: medium
doc-warnings: true
test-warnings: false
max-line-length: 120
ignore-paths:
  - docs
  - docs_theme
ignore-patterns:
  - 'backrefs(?:\\|/)uniprops(?:\\|/)unidata(?:\\|/).+?\.py$'
pep257:
  disable:
    - D202
    - D203
