sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-unittests
    - python: 3.3
      env: TOXENV=py33-unittests
    - python: 3.4
      env: TOXENV=py34-unittests
    - python: 3.5
      env: TOXENV=py35-unittests
    # - python: 3.6
    #   env: TOXENV=py36-unittests
    - python: 2.7
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=spelling
install:
  - pip install tox
  - pip install codecov
addons:
  apt:
    packages:
      - aspell
      - aspell-en
script:
  - tox
after_success:
  - codecov
