language: python
dist: xenial
os: linux

jobs:
  include:
    - python: 3.9-dev
      env: TOXENV=py39

install:
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov
