language: python
dist: xenial
sudo: true

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9-dev
      env: TOXENV=py39
  allow_failures:
    - python: 3.9-dev

install:
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov
